# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        python-version: ["3.7", "3.11"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout comforter
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        cd $GITHUB_WORKSPACE/comforter
        pip install -r requirements.txt
      shell: bash

    - name: Install comforter
      run: |
        cd $GITHUB_WORKSPACE/comforter
        pip install .
      shell: bash

    - name: Test with pytest
      run: |
        cd $GITHUB_WORKSPACE/comforter
        pytest tests
      shell: bash

